var express = require("express");
var app = express();
var PdfPrinter = require("pdfmake");
var fs = require("fs");

// app.use(express.static(__dirname + '/public'));
let fonts = {
  Roboto: {
    normal: "node_modules/roboto-font/fonts/Roboto/roboto-regular-webfont.ttf",
    bold: "node_modules/roboto-font/fonts/Roboto/roboto-bold-webfont.ttf",
    italics: "node_modules/roboto-font/fonts/Roboto/roboto-italic-webfont.ttf",
    bolditalics:
      "node_modules/roboto-font/fonts/Roboto/roboto-bolditalic-webfont.ttf",
  },
};
app.get("/pdf_download", function (req, res) {
  let printer = new PdfPrinter(fonts);
  var dd = {
    pageOrientation: "landscape",
    content: [
      {
        image: `${__dirname}/public/logo.jpg`,
        fit: [30, 30],
        alignment: "left",
      },
      { text: "Holidays List - 2020", style: "header" },
      {
        style: "tableExample",
        table: {
          headerRows: 1,
          heights: [
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
          ],
          widths: [
            "*",
            100,
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "auto",
            "*",
          ],
          body: [
            [
              { text: "Date/ Day", style: "tableHeader" },
              { text: "Holiday Name", style: "tableHeader" },
              { text: "Holiday Type", style: "tableHeader" },
              { text: "Kolkata", style: "tableHeader" },
              { text: "Banglore", style: "tableHeader" },
              { text: "Chennai", style: "tableHeader" },
              { text: "Hyderabad", style: "tableHeader" },
              { text: "Vizag", style: "tableHeader" },
              { text: "Ahmedabad ", style: "tableHeader" },
              { text: "Hyderabad", style: "tableHeader" },
              { text: "Vizag", style: "tableHeader" },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
            [
              { text: "26 Jan 20-Mon", border: [true, true, true, true] },
              {
                text: "Sankrathi/Pongal/ Kite festival",
                border: [true, true, true, true],
              },
              { text: "Mandatory", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "Y", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
              { text: "N", border: [true, true, true, true] },
            ],
          ],
        },
        layout: {
          defaultBorder: false,

          hLineWidth: function (i, node) {
            return i === 0 || i === node.table.body.length ? 1 : 2;
          },
          vLineWidth: function (i, node) {
            return i === 0 || i === node.table.widths.length ? 1 : 0;
          },
          hLineColor: function (i, node) {
            return i === 0 || i === node.table.body.length ? "#edeeee" : "#edeeee";
          },
          vLineColor: function (i, node) {
            return i === 0 || i === node.table.widths.length ? "#edeeee" : "green";
          },
        },
      },
    ],
    styles: {
      header: {
        fontSize: 16,
        bold: true,
        margin: [0, 0, 0, 0],
        alignment: "center",
      },
      tableExample: {
        fontSize: 10,
      },
      tableHeader: {
       lineHeight:2,
        fontSize: 10,
        fillColor: "#c3e9e9",
        color: "#000",
        alignment: "center",
      },
    },
    defaultStyle: {
      alignment: "center",
    },
  };

  // var printer = new PdfPrinter();
  let pdfDoc = printer.createPdfKitDocument(dd);

  // var pdfDoc = PdfPrinter.createPdf(docDefinition);
  pdfDoc.pipe(fs.createWriteStream(`${__dirname}/public/holidayslist.pdf`));
  res.send({ message: "Pdf downloaded successully" });
  pdfDoc.end();
});

var server = app.listen(3000, function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log("Example app listening at http://%s:%s", host, port);
});
