var express = require("express");
var app = express();
var PdfPrinter = require("pdfmake");
var fs = require("fs");
let fonts = {
  Roboto: {
    normal:
      "../node_modules/roboto-font/fonts/Roboto/roboto-regular-webfont.ttf",
    bold: "../node_modules/roboto-font/fonts/Roboto/roboto-bold-webfont.ttf",
    italics:
      "../node_modules/roboto-font/fonts/Roboto/roboto-italic-webfont.ttf",
    bolditalics:
      "../node_modules/roboto-font/fonts/Roboto/roboto-bolditalic-webfont.ttf",
  },
};
app.get("/pdf_download", function (req, res) {
  let printer = new PdfPrinter(fonts);
  var dd = {
    pageOrientation: "landscape",
    content: [
      {
        image: "logo.jpg",
        fit: [50, 50],
        alignment: "left"
      },
      { text: "Holidays List - 2020", style: "header" },
      {
        style: "tableExample",
        table: {
          headerRows: 1,
          heights: [15, "auto", "auto", "auto", "auto", "auto", "auto", "auto"],
          widths: ["*", "auto", "auto", "auto", "auto", "auto", "auto", "*"],
          body: [
            [
              { text: "Date/ Day", style: "tableHeader" },
              { text: "Holiday Name", style: "tableHeader" },
              { text: "Holiday Type", style: "tableHeader" },
              { text: "Kolkata", style: "tableHeader" },
              { text: "Banglore", style: "tableHeader" },
              { text: "Chennai", style: "tableHeader" },
              { text: "Hyderabad", style: "tableHeader" },
              { text: "Vizag", style: "tableHeader" },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
            [
              { text: "2020-01-09", border: [true, false, true, true] },
              { text: "1", border: [true, false, true, true] },
              { text: "Mandatory", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "Yes", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
              { text: "No", border: [true, false, true, true] },
            ],
          ],
        },
        layout: {
          defaultBorder: false,

          hLineWidth: function (i, node) {
            return i === 0 || i === node.table.body.length ? 1 : 1;
          },
          vLineWidth: function (i, node) {
            return i === 0 || i === node.table.widths.length ? 1 : 1;
          },
          hLineColor: function (i, node) {
            return i === 0 || i === node.table.body.length ? "gray" : "gray";
          },
          vLineColor: function (i, node) {
            return i === 0 || i === node.table.widths.length ? "gray" : "gray";
          },
        },
      },
    ],
    styles: {
      header: {
        fontSize: 16,
        bold: true,
        margin: [0, 0, 0, 0],
        alignment: "center",
      },
      tableExample: {
        fontSize: 10,
        margin: [0, 15, 0, 15],
      },
      tableHeader: {
        bold: true,
        fontSize: 10,
        fillColor: "#1cbc9c",
        color: "white",
      },
    },
    defaultStyle: {
      alignment: "center",
    },
  };

  // var docDefinition = {
  //     content: [
  //       {
  //         layout: 'lightHorizontalLines', // optional
  //         table: {
  //           // headers are automatically repeated if the table spans over multiple pages
  //           // you can declare how many rows should be treated as headers
  //           headerRows: 1,
  //           widths: [ '*', 'auto', 100, '*' ],

  //           body: [
  //             [ 'First', 'Second', 'Third', 'The last one' ],
  //             [ 'Value 1', 'Value 2', 'Value 3', 'Value 4' ],
  //             [ { text: 'Bold value', bold: true }, 'Val 2', 'Val 3', 'Val 4' ]
  //           ]
  //         }
  //       }
  //     ]
  //   };

  // var printer = new PdfPrinter();
  let pdfDoc = printer.createPdfKitDocument(dd);

  // var pdfDoc = PdfPrinter.createPdf(docDefinition);
  pdfDoc.pipe(fs.createWriteStream("document.pdf"));
  res.send({ message: "Pdf downloaded successully" });
  pdfDoc.end();
});

var server = app.listen(5000, function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log("Example app listening at http://%s:%s", host, port);
});
